name: Deploy to GitHub Pages

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm install
      - run: npm run generate

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false